import {
  Cpu,
  MonitorPlay,
  CircuitBoard,
  MemoryStick,
  HardDrive,
  Zap,
  Box,
  Fan,
  type LucideIcon,
} from 'lucide-react';

export type ComponentCategory =
  'cpu' | 'gpu' | 'motherboard' | 'ram' | 'storage' | 'psu' | 'case' | 'cooling';

export interface CategoryMeta {
  id: ComponentCategory;
  label: string;
  icon: LucideIcon;
  description: string;
}

export const COMPONENT_CATEGORIES: CategoryMeta[] = [
  { id: 'cpu', label: 'CPU', icon: Cpu, description: 'Processor (Intel / AMD)' },
  { id: 'gpu', label: 'GPU', icon: MonitorPlay, description: 'Graphics Card' },
  {
    id: 'motherboard',
    label: 'Motherboard',
    icon: CircuitBoard,
    description: 'Mainboard (ATX/mATX/ITX)',
  },
  { id: 'ram', label: 'RAM', icon: MemoryStick, description: 'Memory Modules' },
  { id: 'storage', label: 'Storage', icon: HardDrive, description: 'SSD / NVMe / HDD' },
  { id: 'psu', label: 'PSU', icon: Zap, description: 'Power Supply Unit' },
  { id: 'case', label: 'Case', icon: Box, description: 'PC Chassis' },
  { id: 'cooling', label: 'Cooling', icon: Fan, description: 'CPU Cooler / AIO' },
];

export type RamType = 'DDR4' | 'DDR5';
export type FormFactor = 'ITX' | 'mATX' | 'ATX';

export interface BuilderProduct {
  id: string;
  category: ComponentCategory;
  name: string;
  brand: string;
  price: number; // BDT
  keySpec: string;
  popularity: number; // 0–100
  performanceScore: number; // 0–100
  socket?: string; // cpu, motherboard
  ramType?: RamType; // ram, motherboard
  formFactor?: FormFactor; // motherboard; for cases = largest supported
  wattage?: number; // psu output
  tdp?: number; // cpu/gpu power draw
}

export const BUILDER_CATALOG: BuilderProduct[] = [
  // CPU
  {
    id: 'cpu-r5-7600',
    category: 'cpu',
    name: 'AMD Ryzen 5 7600',
    brand: 'AMD',
    price: 25500,
    keySpec: '6 Cores / 12 Threads · 5.1 GHz',
    popularity: 88,
    performanceScore: 72,
    socket: 'AM5',
    tdp: 65,
  },
  {
    id: 'cpu-r7-7800x3d',
    category: 'cpu',
    name: 'AMD Ryzen 7 7800X3D',
    brand: 'AMD',
    price: 52000,
    keySpec: '8 Cores / 16 Threads · 3D V-Cache',
    popularity: 96,
    performanceScore: 90,
    socket: 'AM5',
    tdp: 120,
  },
  {
    id: 'cpu-i5-14600k',
    category: 'cpu',
    name: 'Intel Core i5-14600K',
    brand: 'Intel',
    price: 42500,
    keySpec: '14 Cores / 20 Threads · 5.3 GHz',
    popularity: 84,
    performanceScore: 80,
    socket: 'LGA1700',
    tdp: 125,
  },
  {
    id: 'cpu-i7-14700k',
    category: 'cpu',
    name: 'Intel Core i7-14700K',
    brand: 'Intel',
    price: 58000,
    keySpec: '20 Cores / 28 Threads · 5.6 GHz',
    popularity: 79,
    performanceScore: 88,
    socket: 'LGA1700',
    tdp: 253,
  },
  {
    id: 'cpu-r5-5600',
    category: 'cpu',
    name: 'AMD Ryzen 5 5600',
    brand: 'AMD',
    price: 16500,
    keySpec: '6 Cores / 12 Threads · 4.4 GHz',
    popularity: 90,
    performanceScore: 58,
    socket: 'AM4',
    tdp: 65,
  },
  // GPU
  {
    id: 'gpu-rtx4060',
    category: 'gpu',
    name: 'MSI GeForce RTX 4060 Ventus 8GB',
    brand: 'MSI',
    price: 42000,
    keySpec: '8GB GDDR6 · DLSS 3',
    popularity: 92,
    performanceScore: 62,
    tdp: 115,
  },
  {
    id: 'gpu-rx7800xt',
    category: 'gpu',
    name: 'Sapphire Pulse RX 7800 XT 16GB',
    brand: 'Sapphire',
    price: 68000,
    keySpec: '16GB GDDR6 · RDNA 3',
    popularity: 85,
    performanceScore: 78,
    tdp: 263,
  },
  {
    id: 'gpu-rtx4070ti',
    category: 'gpu',
    name: 'ZOTAC GeForce RTX 4070 Ti Trinity 12GB',
    brand: 'ZOTAC',
    price: 108000,
    keySpec: '12GB GDDR6X · DLSS 3',
    popularity: 81,
    performanceScore: 86,
    tdp: 285,
  },
  {
    id: 'gpu-rtx4090',
    category: 'gpu',
    name: 'ASUS ROG Strix RTX 4090 OC 24GB',
    brand: 'ASUS',
    price: 245000,
    keySpec: '24GB GDDR6X · Flagship',
    popularity: 74,
    performanceScore: 100,
    tdp: 450,
  },
  // Motherboard
  {
    id: 'mobo-b650m-a',
    category: 'motherboard',
    name: 'MSI PRO B650M-A WiFi',
    brand: 'MSI',
    price: 23500,
    keySpec: 'AM5 · DDR5 · mATX',
    popularity: 87,
    performanceScore: 70,
    socket: 'AM5',
    ramType: 'DDR5',
    formFactor: 'mATX',
  },
  {
    id: 'mobo-x670e',
    category: 'motherboard',
    name: 'ASUS ROG Strix X670E-E Gaming',
    brand: 'ASUS',
    price: 62000,
    keySpec: 'AM5 · DDR5 · ATX',
    popularity: 76,
    performanceScore: 92,
    socket: 'AM5',
    ramType: 'DDR5',
    formFactor: 'ATX',
  },
  {
    id: 'mobo-b760m',
    category: 'motherboard',
    name: 'Gigabyte B760M DS3H',
    brand: 'Gigabyte',
    price: 17800,
    keySpec: 'LGA1700 · DDR4 · mATX',
    popularity: 89,
    performanceScore: 62,
    socket: 'LGA1700',
    ramType: 'DDR4',
    formFactor: 'mATX',
  },
  {
    id: 'mobo-z790',
    category: 'motherboard',
    name: 'ASUS TUF Gaming Z790-Plus WiFi',
    brand: 'ASUS',
    price: 41000,
    keySpec: 'LGA1700 · DDR5 · ATX',
    popularity: 82,
    performanceScore: 84,
    socket: 'LGA1700',
    ramType: 'DDR5',
    formFactor: 'ATX',
  },
  {
    id: 'mobo-b550m',
    category: 'motherboard',
    name: 'MSI B550M PRO-VDH WiFi',
    brand: 'MSI',
    price: 13500,
    keySpec: 'AM4 · DDR4 · mATX',
    popularity: 91,
    performanceScore: 55,
    socket: 'AM4',
    ramType: 'DDR4',
    formFactor: 'mATX',
  },
  // RAM
  {
    id: 'ram-vengeance-16-d5',
    category: 'ram',
    name: 'Corsair Vengeance 16GB DDR5-5600',
    brand: 'Corsair',
    price: 8500,
    keySpec: '2×8GB · CL36',
    popularity: 90,
    performanceScore: 72,
    ramType: 'DDR5',
  },
  {
    id: 'ram-tridentz5-32',
    category: 'ram',
    name: 'G.Skill Trident Z5 RGB 32GB DDR5-6000',
    brand: 'G.Skill',
    price: 17500,
    keySpec: '2×16GB · CL30',
    popularity: 86,
    performanceScore: 90,
    ramType: 'DDR5',
  },
  {
    id: 'ram-fury-16-d4',
    category: 'ram',
    name: 'Kingston Fury Beast 16GB DDR4-3200',
    brand: 'Kingston',
    price: 5200,
    keySpec: '2×8GB · CL16',
    popularity: 93,
    performanceScore: 58,
    ramType: 'DDR4',
  },
  {
    id: 'ram-delta-32-d4',
    category: 'ram',
    name: 'TeamGroup T-Force Delta RGB 32GB DDR4-3600',
    brand: 'TeamGroup',
    price: 10800,
    keySpec: '2×16GB · CL18',
    popularity: 78,
    performanceScore: 66,
    ramType: 'DDR4',
  },
  // Storage
  {
    id: 'ssd-980pro-1tb',
    category: 'storage',
    name: 'Samsung 980 Pro 1TB NVMe Gen4',
    brand: 'Samsung',
    price: 13500,
    keySpec: '7,000 MB/s Read',
    popularity: 94,
    performanceScore: 88,
  },
  {
    id: 'ssd-sn770-1tb',
    category: 'storage',
    name: 'WD Black SN770 1TB NVMe',
    brand: 'WD',
    price: 9800,
    keySpec: '5,150 MB/s Read',
    popularity: 89,
    performanceScore: 76,
  },
  {
    id: 'ssd-p3plus-2tb',
    category: 'storage',
    name: 'Crucial P3 Plus 2TB NVMe',
    brand: 'Crucial',
    price: 16500,
    keySpec: '5,000 MB/s · 2TB',
    popularity: 80,
    performanceScore: 72,
  },
  {
    id: 'hdd-barracuda-2tb',
    category: 'storage',
    name: 'Seagate Barracuda 2TB HDD',
    brand: 'Seagate',
    price: 6200,
    keySpec: '7200 RPM · SATA',
    popularity: 71,
    performanceScore: 30,
  },
  // PSU
  {
    id: 'psu-cx650',
    category: 'psu',
    name: 'Corsair CX650 650W 80+ Bronze',
    brand: 'Corsair',
    price: 7200,
    keySpec: '650W · Bronze',
    popularity: 90,
    performanceScore: 55,
    wattage: 650,
  },
  {
    id: 'psu-mwe750',
    category: 'psu',
    name: 'Cooler Master MWE 750W 80+ Gold',
    brand: 'Cooler Master',
    price: 11500,
    keySpec: '750W · Gold · Modular',
    popularity: 85,
    performanceScore: 70,
    wattage: 750,
  },
  {
    id: 'psu-rm850x',
    category: 'psu',
    name: 'Corsair RM850x 850W 80+ Gold',
    brand: 'Corsair',
    price: 16800,
    keySpec: '850W · Gold · Modular',
    popularity: 92,
    performanceScore: 84,
    wattage: 850,
  },
  {
    id: 'psu-vertex1200',
    category: 'psu',
    name: 'Seasonic Vertex 1200W 80+ Platinum',
    brand: 'Seasonic',
    price: 32000,
    keySpec: '1200W · Platinum · ATX 3.0',
    popularity: 68,
    performanceScore: 96,
    wattage: 1200,
  },
  // Case
  {
    id: 'case-h5flow',
    category: 'case',
    name: 'NZXT H5 Flow',
    brand: 'NZXT',
    price: 9800,
    keySpec: 'Mid Tower · up to ATX',
    popularity: 88,
    performanceScore: 74,
    formFactor: 'ATX',
  },
  {
    id: 'case-lancool216',
    category: 'case',
    name: 'Lian Li Lancool 216',
    brand: 'Lian Li',
    price: 12500,
    keySpec: 'Mid Tower · up to ATX',
    popularity: 91,
    performanceScore: 86,
    formFactor: 'ATX',
  },
  {
    id: 'case-nr200p',
    category: 'case',
    name: 'Cooler Master NR200P',
    brand: 'Cooler Master',
    price: 11200,
    keySpec: 'SFF · ITX only',
    popularity: 75,
    performanceScore: 70,
    formFactor: 'ITX',
  },
  {
    id: 'case-4000d',
    category: 'case',
    name: 'Corsair 4000D Airflow',
    brand: 'Corsair',
    price: 11800,
    keySpec: 'Mid Tower · up to ATX',
    popularity: 93,
    performanceScore: 80,
    formFactor: 'ATX',
  },
  // Cooling
  {
    id: 'cool-ag400',
    category: 'cooling',
    name: 'Deepcool AG400 Air Cooler',
    brand: 'Deepcool',
    price: 2800,
    keySpec: '220W TDP · 4 Heatpipes',
    popularity: 87,
    performanceScore: 52,
  },
  {
    id: 'cool-hyper212',
    category: 'cooling',
    name: 'Cooler Master Hyper 212 Black',
    brand: 'Cooler Master',
    price: 3800,
    keySpec: '180W TDP · Air',
    popularity: 90,
    performanceScore: 50,
    // classic budget pick
  },
  {
    id: 'cool-ls520',
    category: 'cooling',
    name: 'Deepcool LS520 240mm AIO',
    brand: 'Deepcool',
    price: 10500,
    keySpec: '240mm Liquid · ARGB',
    popularity: 83,
    performanceScore: 76,
  },
  {
    id: 'cool-kraken360',
    category: 'cooling',
    name: 'NZXT Kraken 360 AIO',
    brand: 'NZXT',
    price: 21500,
    keySpec: '360mm Liquid · LCD',
    popularity: 77,
    performanceScore: 92,
  },
];

export function productsByCategory(category: ComponentCategory): BuilderProduct[] {
  return BUILDER_CATALOG.filter((p) => p.category === category);
}
